### ISSUE TITLE
Bash installer is generated with CRLF linebreaks

### ISSUE THREAD

**Issue by spitfire05** [axodotdev/cargo-dist#181] opened 2023-03-04 20:27 UTC
As in title, the bash installer, for whatever reason, is generated with CRLF, which makes it effectively fail.

```
❯ cargo dist
analyzing workspace:
  portproxy
    [bin] portproxy

 WARN skipping powershell installer: not building any supported platforms (use --artifacts=global)
bundling portproxy-v0.2.0-aarch64-apple-darwin.tar.xz
bundling portproxy-v0.2.0-installer.sh
building cargo target (aarch64-apple-darwin/dist)
 (...)
bundled: /Users/mborejszo/source/portproxy/target/distrib/portproxy-v0.2.0-aarch64-apple-darwin.tar.xz
bundled: /Users/mborejszo/source/portproxy/target/distrib/portproxy-v0.2.0-installer.sh
announcing v0.2.0
  portproxy 0.2.0
    /Users/mborejszo/source/portproxy/target/distrib/portproxy-v0.2.0-installer.sh
    /Users/mborejszo/source/portproxy/target/distrib/portproxy-v0.2.0-aarch64-apple-darwin.tar.xz
      [bin] portproxy
      [misc] LICENSE.md, README.md
```

```
❯ file target/distrib/portproxy-v0.2.0-installer.sh
target/distrib/portproxy-v0.2.0-installer.sh: Bourne-Again shell script text executable, ASCII text, with CRLF, LF line terminators
```

```
❯ bash target/distrib/portproxy-v0.2.0-installer.sh
: command not foundproxy-v0.2.0-installer.sh: line 7:
: command not foundproxy-v0.2.0-installer.sh: line 14:
: invalid optionortproxy-v0.2.0-installer.sh: line 15: set: -
set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
: command not foundproxy-v0.2.0-installer.sh: line 16:
: command not foundproxy-v0.2.0-installer.sh: line 22:
'arget/distrib/portproxy-v0.2.0-installer.sh: line 23: syntax error near unexpected token `{
'arget/distrib/portproxy-v0.2.0-installer.sh: line 23: `download_binary_and_run_installer() {
```

Simple solution may be to run dos2unix conversion on the generated installer string.

**Comment by milesj** [comment] 2023-03-05 22:55
+1 noticed this as well. I've been using my editor to convert to LF.

**Comment by ashleygwilliams** [comment] 2023-03-06 17:35
hey ya'll! thanks for filing, i'm gonna write some tests to repro this and then will work to merge the fix (thanks @spitfire05) and get a 0.0.5 out. this bug is def my fault because i am def the person who recommend the git changes that caused this 😭 https://github.com/axodotdev/cargo-dist/pull/149

**Comment by spitfire05** [comment] 2023-03-06 19:02
Thanks for explaining, I as actually baffled as to why this happens :D

**Comment by ashleygwilliams** [comment] 2023-03-06 20:28
hrmm, so i am struggling to reproduce this error. i've some (quite shoddy, but functional) tests here in #189, and i can't reproduce the error on my own. can you share more and/or an example? 

i do wonder if the wrong linebreaks are baked into our code, but are not committed because we did *fix* this error by adding the git attribute, but didn't "share the fix" since .gitattributes is a per repo setting....

**Comment by spitfire05** [comment] 2023-03-06 21:06
Hmm interesting. I *think* it once generated a non-bugged installer when I was using a locally built `cargo-dist` from master branch, but I could not reproduce it later. Anyway, the simplest way I am reproducing this bug is:

```
❯ git clone https://github.com/axodotdev/cargo-dist.git
Cloning into 'cargo-dist'...
remote: Enumerating objects: 2037, done.
remote: Counting objects: 100% (633/633), done.
remote: Compressing objects: 100% (382/382), done.
remote: Total 2037 (delta 305), reused 437 (delta 234), pack-reused 1404
Receiving objects: 100% (2037/2037), 2.39 MiB | 8.06 MiB/s, done.
Resolving deltas: 100% (1062/1062), done.

~/source
❯ cd cargo-dist/

cargo-dist [ main][🦀 v1.67.1]
❯ cd cargo-dist/

cargo-dist/cargo-dist [ main][📦 v0.0.4][🦀 v1.67.1]
❯ cargo dist
analyzing workspace:
  cargo-dist
    [bin] cargo-dist
  cargo-dist-schema (no binaries)

 WARN skipping powershell installer: not building any supported platforms (use --artifacts=global)
bundling cargo-dist-v0.0.4-aarch64-apple-darwin.tar.xz
bundling cargo-dist-v0.0.4-installer.sh
building cargo target (aarch64-apple-darwin/dist)
   (...)
   Compiling cargo-dist v0.0.4 (/Users/mborejszo/source/cargo-dist/cargo-dist)
    Finished dist [optimized] target(s) in 24.61s
bundled: /Users/mborejszo/source/cargo-dist/target/distrib/cargo-dist-v0.0.4-aarch64-apple-darwin.tar.xz
bundled: /Users/mborejszo/source/cargo-dist/target/distrib/cargo-dist-v0.0.4-installer.sh
announcing v0.0.4
  cargo-dist 0.0.4
    /Users/mborejszo/source/cargo-dist/target/distrib/cargo-dist-v0.0.4-installer.sh
    /Users/mborejszo/source/cargo-dist/target/distrib/cargo-dist-v0.0.4-aarch64-apple-darwin.tar.xz
      [bin] cargo-dist
      [misc] CHANGELOG.md, LICENSE-APACHE, LICENSE-MIT, README.md

cargo-dist/cargo-dist [ main][📦 v0.0.4][🦀 v1.67.1][⏱ 27s]
❯ file ../target/distrib/cargo-dist-v0.0.4-installer.sh
../target/distrib/cargo-dist-v0.0.4-installer.sh: Bourne-Again shell script text executable, ASCII text, with CRLF, LF line terminators
```

bin version used (installed with `cargo install`):
```
❯ cargo dist --version
cargo-dist 0.0.4
```

I am currently on an M1 mac, will try to check on Windows tomorrow.

Hope that helps.

**Comment by ashleygwilliams** [comment] 2023-03-06 23:01
@spitfire05 so i've gone ahead and plugged in your exact steps into the CI and cannot reproduce (https://github.com/axodotdev/cargo-dist/actions/runs/4348704371/jobs/7597540441#step:5:5). to be abundantly clear: i 100% believe you are experiencing this, just realizing that things are perhaps more complicated than they may seem. 

gonna keep looking into this and also run cargo-dist on oranda to see if i can repro on a separate repo.

**Comment by ashleygwilliams** [comment] 2023-03-06 23:45
could some folks with this issue run `cat -e` on their offending generated installer(s) and share them here? this will (maybe??) help me identify where the line endings are being generated since i can't reproduce (yet)

**Comment by milesj** [comment] 2023-03-07 08:04
Here you are:

```
# CI that:^M$
#^M$
# * checks for a Git Tag that looks like a release^M$
# * creates a Github Release�M-^D� and fills in its text^M$
# * builds artifacts with cargo-dist (executable-zips, installers)^M$
# * uploads those artifacts to the Github Release�M-^D�^M$
#^M$
# Note that the Github Release�M-^D� will be created before the artifacts,^M$
# so there will be a few minutes where the release has no artifacts^M$
# and then they will slowly trickle in, possibly failing. To make^M$
# this more pleasant we mark the release as a "draft" until all^M$
# artifacts have been successfully uploaded. This allows you to^M$
# choose what to do with partial successes and avoids spamming^M$
# anyone with notifications before the release is actually ready.^M$
name: Release^M$
^M$
permissions:^M$
  contents: write^M$
^M$
# This task will run whenever you push a git tag that looks like a version^M$
# like "v1", "v1.2.0", "v0.1.0-prerelease01", "my-app-v1.0.0", etc.^M$
# The version will be roughly parsed as ({PACKAGE_NAME}-)?v{VERSION}, where^M$
# PACKAGE_NAME must be the name of a Cargo package in your workspace, and VERSION^M$
# must be a Cargo-style SemVer Version.^M$
#^M$
# If PACKAGE_NAME is specified, then we will create a Github Release�M-^D� for that^M$
# package (erroring out if it doesn't have the given version or isn't cargo-dist-able).^M$
#^M$
# If PACKAGE_NAME isn't specified, then we will create a Github Release�M-^D� for all^M$
# (cargo-dist-able) packages in the workspace with that version (this is mode is^M$
# intended for workspaces with only one dist-able package, or with all dist-able^M$
# packages versioned/released in lockstep).^M$
#^M$
# If you push multiple tags at once, separate instances of this workflow will^M$
# spin up, creating an independent Github Release�M-^D� for each one.^M$
#^M$
# If there's a prerelease-style suffix to the version then the Github Release�M-^D�^M$
# will be marked as a prerelease.^M$
on:^M$
  push:^M$
    tags:^M$
      - '*-?v[0-9]+*'^M$
^M$
jobs:^M$
  # Create the Github Release�M-^D� so the packages have something to be uploaded to^M$
  create-release:^M$
    runs-on: ubuntu-latest^M$
    outputs:^M$
      has-releases: ${{ steps.create-release.outputs.has-releases }}^M$
    env:^M$
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}^M$
    steps:^M$
      - uses: actions/checkout@v3^M$
      - name: Install Rust^M$
        run: rustup update 1.67.0 --no-self-update && rustup default 1.67.0^M$
      - name: Install cargo-dist^M$
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.0.4/cargo-dist-v0.0.4-installer.sh | sh^M$
      - id: create-release^M$
        run: |^M$
          cargo dist manifest --tag=${{ github.ref_name }} --artifacts=all --no-local-paths --output-format=json > dist-manifest.json^M$
          echo "dist manifest ran successfully"^M$
          cat dist-manifest.json^M$
        ^M$
          # Create the Github Release�M-^D� based on what cargo-dist thinks it should be^M$
          ANNOUNCEMENT_TITLE=$(cat dist-manifest.json | jq --raw-output ".announcement_title")^M$
          IS_PRERELEASE=$(cat dist-manifest.json | jq --raw-output ".announcement_is_prerelease")^M$
          cat dist-manifest.json | jq --raw-output ".announcement_github_body" > new_dist_announcement.md^M$
          gh release create ${{ github.ref_name }} --draft --prerelease="$IS_PRERELEASE" --title="$ANNOUNCEMENT_TITLE" --notes-file=new_dist_announcement.md^M$
          echo "created announcement!"^M$
^M$
          # Upload the manifest to the Github Release�M-^D�^M$
          gh release upload ${{ github.ref_name }} dist-manifest.json^M$
          echo "uploaded manifest!"^M$
^M$
          # Disable all the upload-artifacts tasks if we have no actual releases^M$
          HAS_RELEASES=$(cat dist-manifest.json | jq --raw-output ".releases != null")^M$
          echo "has-releases=$HAS_RELEASES" >> "$GITHUB_OUTPUT"^M$
^M$
  # Build and packages all the things^M$
  upload-artifacts:^M$
    # Let the initial task tell us to not run (currently very blunt)^M$
    needs: create-release^M$
    if: ${{ needs.create-release.outputs.has-releases == 'true' }}^M$
    strategy:^M$
      matrix:^M$
        # For these target platforms^M$
        include:$
        - os: macos-11$
          dist-args: --artifacts=local --target=aarch64-apple-darwin --target=x86_64-apple-darwin$
          install-dist: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.0.4/cargo-dist-v0.0.4-installer.sh | sh$
        - os: ubuntu-20.04$
          dist-args: --artifacts=local --target=x86_64-unknown-linux-gnu$
          install-dist: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.0.4/cargo-dist-v0.0.4-installer.sh | sh$
        - os: windows-2019$
          dist-args: --artifacts=local --target=x86_64-pc-windows-msvc$
          install-dist: irm  https://github.com/axodotdev/cargo-dist/releases/download/v0.0.4/cargo-dist-v0.0.4-installer.ps1 | iex^M$
^M$
    runs-on: ${{ matrix.os }}^M$
    env:^M$
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}^M$
    steps:^M$
      - uses: actions/checkout@v3^M$
      - name: Install Rust^M$
        run: rustup update 1.67.0 --no-self-update && rustup default 1.67.0^M$
      - name: Install cargo-dist^M$
        run: ${{ matrix.install-dist }}^M$
      - name: Run cargo-dist^M$
        # This logic is a bit janky because it's trying to be a polyglot between^M$
        # powershell and bash since this will run on windows, macos, and linux!^M$
        # The two platforms don't agree on how to talk about env vars but they^M$
        # do agree on 'cat' and '$()' so we use that to marshal values between commands.^M$
        run: |^M$
          # Actually do builds and make zips and whatnot^M$
          cargo dist build --tag=${{ github.ref_name }} --output-format=json ${{ matrix.dist-args }} > dist-manifest.json^M$
          echo "dist ran successfully"^M$
          cat dist-manifest.json^M$
^M$
          # Parse out what we just built and upload it to the Github Release�M-^D�^M$
          cat dist-manifest.json | jq --raw-output ".artifacts[]?.path | select( . != null )" > uploads.txt^M$
          echo "uploading..."^M$
          cat uploads.txt^M$
          gh release upload ${{ github.ref_name }} $(cat uploads.txt)^M$
          echo "uploaded!"^M$
^M$
  # Mark the Github Release�M-^D� as a non-draft now that everything has succeeded!^M$
  publish-release:^M$
    # Only run after all the other tasks, but it's ok if upload-artifacts was skipped^M$
    needs: [create-release, upload-artifacts]^M$
    if: ${{ always() && needs.create-release.result == 'success' && (needs.upload-artifacts.result == 'skipped' || needs.upload-artifacts.result == 'success') }}^M$
    runs-on: ubuntu-latest^M$
    env:^M$
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}^M$
    steps:^M$
      - uses: actions/checkout@v3^M$
      - name: mark release as non-draft^M$
        run: |^M$
          gh release edit ${{ github.ref_name }} --draft=false%
```

**Comment by milesj** [comment] 2023-03-07 08:04
Anytime I run `cargo dist generate-ci` it adds back the CR.

**Comment by spitfire05** [comment] 2023-03-07 09:15
> Anytime I run `cargo dist generate-ci` it adds back the CR.

So, that's another issue, I was referring specifically to the shell installers here (bash, powershell).

Anyway @milesj does this actually make the Github Actions mis-parse the CI yaml? I always assumed they can handle both LF and CRLF notation.

**Comment by spitfire05** [comment] 2023-03-07 09:32
@ashleygwilliams on Windows, the PowerShell installer seems to be generated with 100% CRLF (as we'd expect). On Ubuntu 22.04 (WSL), the issue is present (Bash installer with mix of CRLF).

```shell
mborejszo@GYM5S73:~/source/cargo-dist/cargo-dist$ file ../target/distrib/cargo-dist-v0.0.4-installer.sh
../target/distrib/cargo-dist-v0.0.4-installer.sh: Bourne-Again shell script, ASCII text executable, with CRLF, LF line terminators
mborejszo@GYM5S73:~/source/cargo-dist/cargo-dist$ cat -e ../target/distrib/cargo-dist-v0.0.4-installer.sh
#!/bin/bash^M$
#^M$
# Licensed under the MIT license^M$
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your^M$
# option. This file may not be copied, modified, or distributed^M$
# except according to those terms.^M$
^M$
# This is just a little script that can be downloaded from the internet to^M$
# install $APP_NAME. It downloads the tarball from ARTIFACT_DOWNLOAD_URL,^M$
# and extracts it to ~/.cargo/bin/^M$
#^M$
# In the future this script will gain extra features, but for now it's^M$
# intentionally very simplistic to avoid shipping broken things.^M$
^M$
set -u^M$
^M$
# FIXME: patch in the repo's URL for suggesting filling an issue^M$
# REPO="{{REPO_URL}}"^M$
APP_NAME="cargo-dist"^M$
APP_VERSION="0.0.4"^M$
ARTIFACT_DOWNLOAD_URL="https://github.com/axodotdev/cargo-dist/releases/download/v0.0.4"^M$
^M$
download_binary_and_run_installer() {^M$
    downloader --check^M$
    need_cmd mktemp^M$
    need_cmd chmod^M$
    need_cmd mkdir^M$
    need_cmd rm^M$
    need_cmd rmdir^M$
    need_cmd tar^M$
    need_cmd which^M$
    need_cmd dirname^M$
    need_cmd awk^M$
    need_cmd cut^M$
^M$
^M$
    get_architecture || return 1^M$
    local _arch="$RETVAL"^M$
    assert_nz "$_arch" "arch"^M$
^M$
    local _bins=""^M$
    local _zip_ext=""^M$
    local _artifact_name=""^M$
^M$
    # This """lookup table""" is generated by cargo-dist ^M$
    case "$_arch" in $
        "x86_64-unknown-linux-gnu")$
            _artifact_name="cargo-dist-v0.0.4-x86_64-unknown-linux-gnu.tar.xz"$
            _zip_ext=".tar.xz"$
            _bins="cargo-dist"$
            ;;^M$
        *)^M$
            err "there isn't a package for $_arch"^M$
            ;;^M$
    esac^M$
^M$
    # download the zip^M$
    local _url="$ARTIFACT_DOWNLOAD_URL/$_artifact_name"^M$
    local _dir="$(mktemp -d 2>/dev/null || ensure mktemp -d -t $APP_NAME)"^M$
    local _file="$_dir/input$_zip_ext"^M$
^M$
    say "downloading $APP_NAME $APP_VERSION ${_arch}" 1>&2^M$
    say "  from $_url" 1>&2^M$
    say "  to $_file" 1>&2^M$
^M$
    ensure mkdir -p "$_dir"^M$
    downloader "$_url" "$_file"^M$
    if [ $? != 0 ]; then^M$
      say "failed to download $_url"^M$
      say "this may be a standard network error, but it may also indicate"^M$
      say "that $APP_NAME's release process is not working. When in doubt"^M$
      say "please feel free to open an issue!"^M$
      # say "$REPO/issues/new/choose"^M$
      exit 1^M$
    fi^M$
^M$
    # unpack the zip^M$
    say "unpacking" 1>&2^M$
    ensure tar xf "$_file" --strip-components 1 -C "$_dir"^M$
    for _bin_name in $_bins; do^M$
        say "  unpacked $_bin_name"^M$
    done^M$
^M$
    install "$_dir" "$_bins" "$@"^M$
    local _retval=$?^M$
^M$
    ignore rm -rf "$_dir"^M$
^M$
    return "$_retval"^M$
}^M$
^M$
install() {^M$
    # FIXME: prefer $CARGO_HOME over $HOME/.cargo/ if available^M$
    # FIXME: let the user choose the dir to install to^M$
    local _install_dir="$HOME/.cargo/bin/"^M$
    say "installing to $_install_dir"^M$
    mkdir -p "$_install_dir"^M$
^M$
    # copy all the binaries to the install dir^M$
    local _src_dir="$1"^M$
    local _bins="$2"^M$
    for _bin_name in $_bins; do^M$
        local _bin="$_src_dir/$_bin_name"^M$
        cp "$_bin" "$_install_dir"^M$
    done^M$
    ^M$
    say "everything's installed!"^M$
}^M$
^M$
get_architecture() {^M$
    local _ostype="$(uname -s)"^M$
    local _cputype="$(uname -m)"^M$
^M$
    if [ "$_ostype" = Darwin -a "$_cputype" = i386 ]; then^M$
        # Darwin `uname -s` lies^M$
        if sysctl hw.optional.x86_64 | grep -q ': 1'; then^M$
            local _cputype=x86_64^M$
        fi^M$
    fi^M$
^M$
    if [ "$_ostype" = Darwin -a "$_cputype" = arm64 ]; then^M$
        # Darwin `uname -s` doesn't seem to lie on Big Sur^M$
        # but the cputype we want is called aarch64, not arm64 (they are equivalent)^M$
        local _cputype=aarch64^M$
    fi^M$
^M$
    case "$_ostype" in^M$
        Linux)^M$
            if has_required_glibc; then^M$
                local _ostype=unknown-linux-gnu^M$
            else^M$
                local _ostype=unknown-linux-musl^M$
                say "Downloading musl binary."^M$
            fi^M$
            ;;^M$
^M$
        Darwin)^M$
            local _ostype=apple-darwin^M$
            ;;^M$
^M$
        MINGW* | MSYS* | CYGWIN*)^M$
            local _ostype=pc-windows-msvc^M$
            ;;^M$
^M$
        *)^M$
            err "no precompiled binaries available for OS: $_ostype"^M$
            ;;^M$
    esac^M$
^M$
    case "$_cputype" in^M$
        # these are the only two acceptable values for cputype^M$
        x86_64 | aarch64 )^M$
            ;;^M$
        *)^M$
            err "no precompiled binaries available for CPU architecture: $_cputype"^M$
^M$
    esac^M$
^M$
    local _arch="$_cputype-$_ostype"^M$
^M$
    RETVAL="$_arch"^M$
}^M$
^M$
say() {^M$
    local green=`tput setaf 2 2>/dev/null || echo ''`^M$
    local reset=`tput sgr0 2>/dev/null || echo ''`^M$
    echo "$1"^M$
}^M$
^M$
err() {^M$
    local red=`tput setaf 1 2>/dev/null || echo ''`^M$
    local reset=`tput sgr0 2>/dev/null || echo ''`^M$
    say "${red}ERROR${reset}: $1" >&2^M$
    exit 1^M$
}^M$
^M$
has_required_glibc() {^M$
    local _ldd_version="$(ldd --version 2>&1 | head -n1)"^M$
    # glibc version string is inconsistent across distributions^M$
    # instead check if the string does not contain musl (case insensitive)^M$
    if echo "${_ldd_version}" | grep -iv musl >/dev/null; then^M$
        local _glibc_version=$(echo "${_ldd_version}" | awk 'NR==1 { print $NF }')^M$
        local _glibc_major_version=$(echo "${_glibc_version}" | cut -d. -f1)^M$
        local _glibc_min_version=$(echo "${_glibc_version}" | cut -d. -f2)^M$
        local _min_major_version=2^M$
        local _min_minor_version=17^M$
        if [ "${_glibc_major_version}" -gt "${_min_major_version}" ] \^M$
            || { [ "${_glibc_major_version}" -eq "${_min_major_version}" ] \^M$
            && [ "${_glibc_min_version}" -ge "${_min_minor_version}" ]; }; then^M$
            return 0^M$
        else^M$
            say "This operating system needs glibc >= ${_min_major_version}.${_min_minor_version}, but only has ${_libc_version} installed."^M$
        fi^M$
    else^M$
        say "This operating system does not support dynamic linking to glibc."^M$
    fi^M$
^M$
    return 1^M$
}^M$
^M$
need_cmd() {^M$
    if ! check_cmd "$1"^M$
    then err "need '$1' (command not found)"^M$
    fi^M$
}^M$
^M$
check_cmd() {^M$
    command -v "$1" > /dev/null 2>&1^M$
    return $?^M$
}^M$
^M$
need_ok() {^M$
    if [ $? != 0 ]; then err "$1"; fi^M$
}^M$
^M$
assert_nz() {^M$
    if [ -z "$1" ]; then err "assert_nz $2"; fi^M$
}^M$
^M$
# Run a command that should never fail. If the command fails execution^M$
# will immediately terminate with an error showing the failing^M$
# command.^M$
ensure() {^M$
    "$@"^M$
    need_ok "command failed: $*"^M$
}^M$
^M$
# This is just for indicating that commands' results are being^M$
# intentionally ignored. Usually, because it's being executed^M$
# as part of error handling.^M$
ignore() {^M$
    "$@"^M$
}^M$
^M$
# This wraps curl or wget. Try curl first, if not installed,^M$
# use wget instead.^M$
downloader() {^M$
    if check_cmd curl^M$
    then _dld=curl^M$
    elif check_cmd wget^M$
    then _dld=wget^M$
    else _dld='curl or wget' # to be used in error message of need_cmd^M$
    fi^M$
^M$
    if [ "$1" = --check ]^M$
    then need_cmd "$_dld"^M$
    elif [ "$_dld" = curl ]^M$
    then curl -sSfL "$1" -o "$2"^M$
    elif [ "$_dld" = wget ]^M$
    then wget "$1" -O "$2"^M$
    else err "Unknown downloader"   # should not reach here^M$
    fi^M$
}^M$
^M$
```

**Comment by ashleygwilliams** [comment] 2023-03-07 13:15
@milesj , @spitfire05 , thank you so much!! this is very helpful. i am still not 100% certain why i can't reproduce but i think accepting #182 is the right call. given that i can't reproduce, i'll be taking ya'lls word for it that this fixes the issue (though it certain would make sense to logically and was what @Gankra originally implemented in #148 before my (apparently foolish) git config suggestion) - i'm going to cut a 0.0.5-prerelease and will message here to ask if ya'll could test it (assuming you are willing?)

**Comment by spitfire05** [comment] 2023-03-07 13:37
Sure thing, I will test it when it's ready 😄

**Comment by ashleygwilliams** [comment] 2023-03-07 20:08
https://github.com/axodotdev/cargo-dist/releases/tag/v0.0.5-prerelease.1 here's the pre-release, didn't publish to crates but if you need me to lemme know

**Comment by spitfire05** [comment] 2023-03-07 20:57
Looks good on mac!

```shell
cargo-dist/cargo-dist (1cc4c96) [📦 v0.0.5-prerelease.1][🦀 v1.67.1]
❯ rm -r ../target

cargo-dist/cargo-dist (1cc4c96) [📦 v0.0.5-prerelease.1][🦀 v1.67.1]
❯ cargo run -- dist
   (...)
    Finished dev [unoptimized + debuginfo] target(s) in 10.82s
     Running `/Users/mborejszo/source/cargo-dist/target/debug/cargo-dist dist`
analyzing workspace:
  cargo-dist
    [bin] cargo-dist
  cargo-dist-schema (no binaries)

 WARN skipping powershell installer: not building any supported platforms (use --artifacts=global)
bundling cargo-dist-v0.0.5-prerelease.1-aarch64-apple-darwin.tar.xz
bundling cargo-dist-v0.0.5-prerelease.1-installer.sh
building cargo target (aarch64-apple-darwin/dist)
   (...)
    Finished dist [optimized] target(s) in 20.91s
bundled: /Users/mborejszo/source/cargo-dist/target/distrib/cargo-dist-v0.0.5-prerelease.1-aarch64-apple-darwin.tar.xz
bundled: /Users/mborejszo/source/cargo-dist/target/distrib/cargo-dist-v0.0.5-prerelease.1-installer.sh
announcing v0.0.5-prerelease.1
  cargo-dist 0.0.5-prerelease.1
    /Users/mborejszo/source/cargo-dist/target/distrib/cargo-dist-v0.0.5-prerelease.1-installer.sh
    /Users/mborejszo/source/cargo-dist/target/distrib/cargo-dist-v0.0.5-prerelease.1-aarch64-apple-darwin.tar.xz
      [bin] cargo-dist
      [misc] CHANGELOG.md, LICENSE-APACHE, LICENSE-MIT, README.md

cargo-dist/cargo-dist (1cc4c96) [📦 v0.0.5-prerelease.1][🦀 v1.67.1]
❯ file ../target/distrib/cargo-dist-v0.0.5-prerelease.1-installer.sh
../target/distrib/cargo-dist-v0.0.5-prerelease.1-installer.sh: Bourne-Again shell script text executable, ASCII text
```

**Comment by ashleygwilliams** [comment] 2023-03-07 21:01
reopening this just because i need to add the newline sanitization to the yml to consider this complete. should be ready momentarily

**Comment by ashleygwilliams** [comment] 2023-03-07 21:03
@spitfire05 lol i am in awe that it now works for you- @Gankra tried a fresh clone and ran into issues and so we decided we were gonna just accept #182 (we still are, i think it'll help me sleep better at night regardless).

**Comment by spitfire05** [comment] 2023-03-07 21:06
This is becoming more peculiar on hourly basis, huh! 😮

Yeah at this point I'd also vote for "better be sure" approach of #182, as I think no-one really knows why this happens (or does not happen).

**Comment by ashleygwilliams** [comment] 2023-03-07 21:13
i do wonder if this is a result of the bootstrapping that cargo-dist does... (cargo-dist is itself released by a previous version of itself) but regardless, i have merged PRs that should 100% ensure that the line endings are accurate and am cutting another pre-release now. thank you so much for your help on this!! will def give you a shout in the announcement!

**Comment by spitfire05** [comment] 2023-03-07 21:18
@ashleygwilliams I am happy to help, cargo-dist is a very interesting project, that makes the release-development life just a little bit easier 😄 

As for your remark about bootstrapping.. yeah that may be true, in my checking of .5-prereleae.1 I built `cargo-dist` in-place, which may explain why it worked for me this time.. but not the other issues of @Gankra you've mentioned 🤔

**Comment by Gankra** [comment] 2023-03-15 19:46
0.0.5 released with the fix

**Comment by ashleygwilliams** [comment] 2023-03-15 20:10
closing this now- if ya'll run into issues still feel free to reopen. thanks so much again for your patience and help!

**Closed by ashleygwilliams** 2023-03-15 20:10 UTC
Labels: bug, status - pull request attached
