### ISSUE TITLE
Respect `publish = false`

### ISSUE THREAD

**Issue by Aloso** [axodotdev/cargo-dist#80] opened 2023-02-01 23:15 UTC
My project containts two binary crates. One has this in the `Cargo.toml`:

```toml
[package]
# ...
publish = false
```

`cargo dist` builds both binary crates, but it should skip the one where `publish = false` is set.

**Comment by Gankra** [comment] 2023-02-08 22:30
dupe of #79

**Closed by Gankra** 2023-02-08 22:30 UTC
