### ISSUE TITLE
Support for distributing dynamic library

### ISSUE THREAD

**Issue by nurmohammed840** [axodotdev/cargo-dist#179] opened 2023-03-02 06:23 UTC

**Comment by ashleygwilliams** [comment] 2023-03-28 23:36
@nurmohammed840 would love more info on this request if you have the time to share more :)

**Comment by Michael-F-Bryan** [comment] 2023-04-16 18:06
I came here because the thing I'm working on includes both a CLI (in a `foo-cli` crate) and a C API (in a `foo-c-api` crate). 

@ashleygwilliams when distributing a C API you'll normally want to include a couple things:

- Header file (can be considered a static file in your repo for all intents and purposes)
- Dynamic library (i.e. use the `cdylib` crate type to generate `libfoo.so` or `libfoo.dll`)
- Static library (i.e. use the `staticlib` crate type to generate `libfoo.a` or `libfoo.lib`)

**Comment by penberg** [comment] 2024-07-17 05:44
I would love to use `cargo dist` to distribute a static library as well: https://github.com/penberg/limbo/issues/162

**Comment by mistydemeo** [comment] 2024-07-17 16:22
We're in the process of shipping this! It should be in the next release.

**Comment by mistydemeo** [comment] 2024-07-17 22:51
As of PR #1214, we'll support static libraries too.

**Comment by penberg** [comment] 2024-07-23 13:23
Hey @mistydemeo! I see `install-libraries` in https://opensource.axo.dev/cargo-dist/book/reference/config.html?highlight=staticlib#install-libraries. However, I don't think it's available in 0.19.0 -- a documentation bug?

**Comment by Gankra** [comment] 2024-07-23 19:28
Ah yes, documentation bug -- it's slated for 0.20.0, but it *is* largely implemented already.

The current work can be found in this prerelease, and should works as documented:

https://github.com/axodotdev/cargo-dist/releases/tag/v0.20.0-prerelease.3

----

Before we ship the proper release it we need some clarification on what installers you'd like to be using, on which platforms, and if there's any specific platform-specific behaviour you expect/require. I think this might have gotten discussed in some other places but it would be good to write them down somewhere.

Current behaviour is:

* the tarball packs all the files flat and together
* the homebrew installer unpacks each kind of file to the appropriate package manager bin/lib dirs
* the shell/powershell installers dump the files flat into the same dir on PATH
  * this is *presumably* undesirable and should get adjusted to some more appropriate per-platform/configurable behaviour, but **unclear which knobs/defaults we want**
* ??? with the msi installer unclear it even knows about the files

**Comment by mistydemeo** [comment] 2024-07-23 20:09
I've corrected the minimum version in the docs; sorry for the confusion!

**Comment by penberg** [comment] 2024-07-24 06:08
Hey @Gankra! I am just using the shell installer:

https://github.com/penberg/limbo/blob/main/Cargo.toml

I will try out the pre-release, thanks!

**Comment by penberg** [comment] 2024-07-24 06:10
I don't see `cargo dist plan` pick up the static library, is that expected?

```
penberg@vonneumann limbo % cargo dist plan
announcing v0.0.1
  limbo 0.0.1
    source.tar.gz
      [checksum] source.tar.gz.sha256
    limbo-installer.sh
    limbo-aarch64-apple-darwin-update
    limbo-aarch64-apple-darwin.tar.xz
      [bin] limbo
      [misc] CHANGELOG.md, LICENSE.md, README.md
      [checksum] limbo-aarch64-apple-darwin.tar.xz.sha256
    limbo-x86_64-apple-darwin-update
    limbo-x86_64-apple-darwin.tar.xz
      [bin] limbo
      [misc] CHANGELOG.md, LICENSE.md, README.md
      [checksum] limbo-x86_64-apple-darwin.tar.xz.sha256
    limbo-x86_64-pc-windows-msvc-update
    limbo-x86_64-pc-windows-msvc.zip
      [bin] limbo.exe
      [misc] CHANGELOG.md, LICENSE.md, README.md
      [checksum] limbo-x86_64-pc-windows-msvc.zip.sha256
    limbo-x86_64-unknown-linux-gnu-update
    limbo-x86_64-unknown-linux-gnu.tar.xz
      [bin] limbo
      [misc] CHANGELOG.md, LICENSE.md, README.md
      [checksum] limbo-x86_64-unknown-linux-gnu.tar.xz.sha256
```

**Comment by mistydemeo** [comment] 2024-07-24 16:17
Did you enable both the new [`package-libraries`](https://opensource.axo.dev/cargo-dist/book/reference/config.html?highlight=staticlib#package-libraries) and [`install-libraries`](https://opensource.axo.dev/cargo-dist/book/reference/config.html?highlight=staticlib#install-libraries) options?

**Comment by penberg** [comment] 2024-07-24 16:29
@mistydemeo Oh, first of all, I was still running 0.19.0. I did not realize `cargo dist init` downgraded the version for me. 🙈

But now with the following options in Cargo.toml:

```
[workspace.metadata.dist]
cargo-dist-version = "0.20.0-prerelease.3"
ci = "github"
package-libraries = ["staticlib"]
installers = ["shell"]
install-libraries = ["staticlib"]
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
pr-run-mode = "plan"
install-path = "~/.limbo"
install-updater = true
dist = false
```

I see the following `cargo dist plan` failure:

```
penberg@vonneumann limbo % cargo dist --version
cargo-dist 0.20.0-prerelease.3
penberg@vonneumann limbo % cargo dist plan
  × Malformed metadata.dist in /Users/penberg/src/penberg/limbo/Cargo.toml
  ╰─▶ staticlib is not a recognized type of library
  help: you can find a reference for the configuration schema at https://opensource.axo.dev/cargo-dist/book/
        reference/config.html
```

**Comment by Gankra** [comment] 2024-07-24 16:34
@penberg ah so in the cargo-dist config we actually explicitly call these "cstaticlib"

rust has this very confusing naming scheme where they did "staticlib (c) and rlib (rust)" and "cdylib (c) and dylib (rust)"

we're currently opting to normalize on a single naming scheme that's less ambiguous

**Comment by mistydemeo** [comment] 2024-07-24 16:36
I'll get the docs fixed - we considered both names, but settled on `cstaticlib` for consistency. Even though it's not the name Rust uses, we felt it was clearer when we're dealing with packaging non-Rust languages.

**Comment by penberg** [comment] 2024-07-24 18:07
I now switched to `cstaticlib`, but `cargo dist plan` still doesn't seem to see the static library:

```
penberg@vonneumann limbo % cargo dist plan
announcing v0.0.1
  limbo 0.0.1
    source.tar.gz
      [checksum] source.tar.gz.sha256
    limbo-installer.sh
    limbo-aarch64-apple-darwin-update
    limbo-aarch64-apple-darwin.tar.xz
      [bin] limbo
      [misc] CHANGELOG.md, LICENSE.md, README.md
      [checksum] limbo-aarch64-apple-darwin.tar.xz.sha256
    limbo-x86_64-apple-darwin-update
    limbo-x86_64-apple-darwin.tar.xz
      [bin] limbo
      [misc] CHANGELOG.md, LICENSE.md, README.md
      [checksum] limbo-x86_64-apple-darwin.tar.xz.sha256
    limbo-x86_64-pc-windows-msvc-update
    limbo-x86_64-pc-windows-msvc.zip
      [bin] limbo.exe
      [misc] CHANGELOG.md, LICENSE.md, README.md
      [checksum] limbo-x86_64-pc-windows-msvc.zip.sha256
    limbo-x86_64-unknown-linux-gnu-update
    limbo-x86_64-unknown-linux-gnu.tar.xz
      [bin] limbo
      [misc] CHANGELOG.md, LICENSE.md, README.md
      [checksum] limbo-x86_64-unknown-linux-gnu.tar.xz.sha256
```

You can see the Cargo.toml configuration here:

```
# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.20.0-prerelease.3"
# CI backends to support
ci = "github"
# Which kinds of built libraries to include in the final archives
package-libraries = "cstaticlib"
# The installers to generate for each app
installers = ["shell"]
# Which kinds of packaged libraries to install
install-libraries = "cstaticlib"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Publish jobs to run in CI
pr-run-mode = "plan"
# Path that installers should place binaries in
install-path = "~/.limbo"
# Whether to install an updater program
install-updater = true
# Whether to consider the binaries in a package for distribution (defaults true)
dist = false
```

If you need a reproducer, I have one in my branch: https://github.com/penberg/limbo/tree/cargo-dist-staticlib

**Comment by mistydemeo** [comment] 2024-07-24 18:43
It looks like that plan's for the `limbo` crate, which only contains a bin - the cstaticlib is defined in the separate `limbo_sqlite3` crate, which isn't in that plan.

It does look like you've got a distinct version set for `sqlite3_limbo`, so `plan` isn't picking it when trying to pick what to build. You've also got `dist = false`, which is influencing the set of packages being picked. Try setting `sqlite3/Cargo.toml`'s version to the same as the root `Cargo.toml`, and setting `dist = true` in the root `Cargo.toml`.

**Comment by penberg** [comment] 2024-07-24 18:48
This:

```
diff --git a/sqlite3/Cargo.toml b/sqlite3/Cargo.toml
index 1ea36f3..84bfe9f 100644
--- a/sqlite3/Cargo.toml
+++ b/sqlite3/Cargo.toml
@@ -2,12 +2,15 @@

 [package]
 name = "limbo_sqlite3"
-version = "0.0.0"
+version.workspace = true
 authors.workspace = true
 edition.workspace = true
 license.workspace = true
 repository.workspace = true

+[package.metadata.dist]
+dist = true
+
 [lib]
 crate-type = ["cdylib", "staticlib"]
 doc = false
```

Fixes it:

```
  limbo_sqlite3 0.0.1
    source.tar.gz
      [checksum] source.tar.gz.sha256
    limbo_sqlite3-installer.sh
    limbo_sqlite3-aarch64-apple-darwin-update
    limbo_sqlite3-aarch64-apple-darwin.tar.xz
      [cstaticlib] liblimbo_sqlite3.a
      [misc] CHANGELOG.md, LICENSE.md, README.md
      [checksum] limbo_sqlite3-aarch64-apple-darwin.tar.xz.sha256
    limbo_sqlite3-x86_64-apple-darwin-update
    limbo_sqlite3-x86_64-apple-darwin.tar.xz
      [cstaticlib] liblimbo_sqlite3.a
      [misc] CHANGELOG.md, LICENSE.md, README.md
      [checksum] limbo_sqlite3-x86_64-apple-darwin.tar.xz.sha256
    limbo_sqlite3-x86_64-pc-windows-msvc-update
    limbo_sqlite3-x86_64-pc-windows-msvc.zip
      [cstaticlib] limbo_sqlite3.lib
      [misc] CHANGELOG.md, LICENSE.md, README.md
      [checksum] limbo_sqlite3-x86_64-pc-windows-msvc.zip.sha256
    limbo_sqlite3-x86_64-unknown-linux-gnu-update
    limbo_sqlite3-x86_64-unknown-linux-gnu.tar.xz
      [cstaticlib] liblimbo_sqlite3.a
      [misc] CHANGELOG.md, LICENSE.md, README.md
      [checksum] limbo_sqlite3-x86_64-unknown-linux-gnu.tar.xz.sha256
```

Thanks a bunch, @mistydemeo!

**Comment by mistydemeo** [comment] 2024-07-24 21:28
You're welcome! How're you feeling about it now that it's set up?

What are your plans for this? What platforms and installers are you thinking of distributing for?

**Comment by penberg** [comment] 2024-07-25 05:54
Love it! I will distribute the static library as part of the next release for Linux, macOS, and Windows. I am only planning to use the installer script for now. Btw, I think eventually having support for `pkg-config` would be pretty cool too.

**Comment by mistydemeo** [comment] 2024-07-30 16:10
Good call on `pkg-config`; filed an issue. #1251.

**Comment by mistydemeo** [comment] 2024-08-14 17:49
This release is out now, so I'm closing this issue now! We can track future needs in other issues.

**Closed by mistydemeo** 2024-08-14 17:49 UTC
Labels: feature request
