### ISSUE TITLE
build linux musl by default

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/cargo-dist#134] opened 2023-02-16 18:50 UTC
while not entirely simple, there is a known path for compiling musl bins and i think we should be doing it by default - partially because it will help bring us to parity with folks looking to transition to dist

some examples:
- https://github.com/cloudflare/wrangler-legacy/blob/master/.github/workflows/release.yml#L55
- https://github.com/apollographql/rover/blob/27de7ed0ebb56943a1db37b7f22fb649b3e9d801/.circleci/config.yml#L308
- https://github.com/rustwasm/wasm-pack/blob/master/.github/workflows/release.yml#L55

**Comment by Gankra** [comment] 2023-02-16 19:46
dupe of #75 ?

**Closed** 2023-02-16 20:05 UTC
Labels: enhancement
